export function buildEnvContent(cfg) {
  return [
    '# ── vCenter ──────────────────────────────────────────────',
    `VCENTER_HOST=${cfg.vcenter.host}`,
    `VCENTER_USER=${cfg.vcenter.user}`,
    `VCENTER_PASSWORD=${cfg.vcenter.password}`,
    `VCENTER_PORT=${cfg.vcenter.port}`,
    `VCENTER_SSL_VERIFY=${cfg.vcenter.sslVerify}`,
    '',
    '# ── Aruba Central ─────────────────────────────────────────',
    `ARUBA_CENTRAL_BASE_URL=${cfg.aruba.baseUrl}`,
    `ARUBA_CLIENT_ID=${cfg.aruba.clientId}`,
    `ARUBA_CLIENT_SECRET=${cfg.aruba.clientSecret}`,
    `ARUBA_CUSTOMER_ID=${cfg.aruba.customerId}`,
    `ARUBA_ACCESS_TOKEN=${cfg.aruba.accessToken}`,
    '',
    '# ── Aruba Direct switches ─────────────────────────────────',
    `ARUBA_DIRECT_HOSTS=${cfg.arubaDirectSwitches?.hosts ?? ''}`,
    `ARUBA_DIRECT_USER=${cfg.arubaDirectSwitches?.user ?? ''}`,
    `ARUBA_DIRECT_PASSWORD=${cfg.arubaDirectSwitches?.password ?? ''}`,
    `ARUBA_DIRECT_PORT=${cfg.arubaDirectSwitches?.port ?? 443}`,
    `ARUBA_DIRECT_SSH_PORT=${cfg.arubaDirectSwitches?.sshPort ?? 22}`,
    `ARUBA_DIRECT_SSL_VERIFY=${cfg.arubaDirectSwitches?.sslVerify ?? false}`,
    '',
    '# ── HPE Alletra 6000 ─────────────────────────────────────',
    `ALLETRA_HOST=${cfg.alletra.host}`,
    `ALLETRA_USER=${cfg.alletra.user}`,
    `ALLETRA_PASSWORD=${cfg.alletra.password}`,
    `ALLETRA_PORT=${cfg.alletra.port}`,
    '',
    '# ── HPE iLO / Redfish ────────────────────────────────────',
    `ILO_HOSTS=${cfg.ilo?.hosts ?? ''}`,
    `ILO_USER=${cfg.ilo?.user ?? ''}`,
    `ILO_PASSWORD=${cfg.ilo?.password ?? ''}`,
    `ILO_PORT=${cfg.ilo?.port ?? 443}`,
    `ILO_SSL_VERIFY=${cfg.ilo?.sslVerify ?? false}`,
    '',
    '# ── Veeam Backup & Replication ────────────────────────────',
    `VEEAM_HOST=${cfg.veeam.host}`,
    `VEEAM_USER=${cfg.veeam.user}`,
    `VEEAM_PASSWORD=${cfg.veeam.password}`,
    `VEEAM_PORT=${cfg.veeam.port}`,
    '',
    '# ── App ───────────────────────────────────────────────────',
    `CACHE_TTL_SECONDS=${cfg.cacheTtl ?? 60}`,
    `LOG_LEVEL=${cfg.logLevel ?? 'INFO'}`,
    '',
    '# ── Auth ──────────────────────────────────────────────────',
    `API_KEY=${cfg.apiKey ?? ''}`,
    `ALLOWED_ORIGINS=${cfg.allowedOrigins ?? '*'}`,
    '',
    '# ── Alerting ─────────────────────────────────────────────',
    `WEBHOOK_URL=${cfg.alerts?.webhookUrl ?? ''}`,
    `WEBHOOK_FORMAT=${cfg.alerts?.webhookFormat ?? 'teams'}`,
    `ALERT_INTERVAL_SECONDS=${(cfg.alerts?.alertIntervalMinutes ?? 5) * 60}`,
    '',
    `ALERT_VCENTER_IDLE_VMS=${cfg.alerts?.vcenterIdleVms ?? 1}`,
    `ALERT_VCENTER_OVERSIZED_VMS=${cfg.alerts?.vcenterOversizedVms ?? 5}`,
    `ALERT_VCENTER_CLUSTER_CPU_LOW_PCT=${cfg.alerts?.vcenterClusterCpuLowPct ?? 30}`,
    '',
    `ALERT_ARUBA_UNUSED_PORT_PCT=${cfg.alerts?.arubaUnusedPortPct ?? 30}`,
    '',
    `ALERT_ALLETRA_UTIL_HIGH_PCT=${cfg.alerts?.alletraUtilHighPct ?? 80}`,
    `ALERT_ALLETRA_UTIL_LOW_PCT=${cfg.alerts?.alletraUtilLowPct ?? 20}`,
    `ALERT_ALLETRA_EFFICIENCY_MIN=${cfg.alerts?.alletraEfficiencyMin ?? 2.0}`,
    '',
    `ALERT_VEEAM_FAILED_JOBS=${cfg.alerts?.veeamFailedJobs ?? 1}`,
    `ALERT_VEEAM_UNPROTECTED_VMS=${cfg.alerts?.veeamUnprotectedVms ?? 1}`,
    `ALERT_VEEAM_REPO_UTIL_PCT=${cfg.alerts?.veeamRepoUtilPct ?? 80}`,
    '',
    `ALERT_ILO_POWER_CAP_PCT=${cfg.alerts?.iloPowerCapPct ?? 90.0}`,
    `ALERT_ILO_ERROR_COUNT=${cfg.alerts?.iloErrorCount ?? 1}`,
  ].join('\n')
}
