export function buildEnvContent(cfg) {
  return [
    '# ── vCenter ──────────────────────────────────────────────',
    `VCENTER_HOST=${cfg.vcenter.host}`,
    `VCENTER_USER=${cfg.vcenter.user}`,
    `VCENTER_PASSWORD=${cfg.vcenter.password ?? ''}`,
    `VCENTER_PORT=${cfg.vcenter.port}`,
    `VCENTER_SSL_VERIFY=${cfg.vcenter.sslVerify}`,
    '',
    '# ── Aruba Central ─────────────────────────────────────────',
    `ARUBA_CENTRAL_BASE_URL=${cfg.aruba.baseUrl}`,
    `ARUBA_CLIENT_ID=${cfg.aruba.clientId}`,
    `ARUBA_CLIENT_SECRET=${cfg.aruba.clientSecret ?? ''}`,
    `ARUBA_CUSTOMER_ID=${cfg.aruba.customerId}`,
    `ARUBA_ACCESS_TOKEN=${cfg.aruba.accessToken ?? ''}`,
    '',
    '# ── Aruba Wireless controller (standalone) ───────────────',
    `ARUBA_WIRELESS_HOST=${cfg.arubaWireless?.host ?? ''}`,
    `ARUBA_WIRELESS_USER=${cfg.arubaWireless?.user ?? ''}`,
    `ARUBA_WIRELESS_PASSWORD=${cfg.arubaWireless?.password ?? ''}`,
    `ARUBA_WIRELESS_PORT=${cfg.arubaWireless?.port ?? 4343}`,
    '',
    '# ── Aruba Direct switches ─────────────────────────────────',
    `ARUBA_DIRECT_HOSTS=${cfg.arubaDirectSwitches?.hosts ?? ''}`,
    `ARUBA_DIRECT_USER=${cfg.arubaDirectSwitches?.user ?? ''}`,
    `ARUBA_DIRECT_PASSWORD=${cfg.arubaDirectSwitches?.password ?? ''}`,
    `ARUBA_DIRECT_PORT=${cfg.arubaDirectSwitches?.port ?? 443}`,
    `ARUBA_DIRECT_SSH_PORT=${cfg.arubaDirectSwitches?.sshPort ?? 22}`,
    `ARUBA_DIRECT_SSL_VERIFY=${cfg.arubaDirectSwitches?.sslVerify ?? false}`,
    '',
    '# ── HPE Alletra 6000 ─────────────────────────────────────',
    `ALLETRA_HOST=${cfg.alletra.host}`,
    `ALLETRA_USER=${cfg.alletra.user}`,
    `ALLETRA_PASSWORD=${cfg.alletra.password ?? ''}`,
    `ALLETRA_PORT=${cfg.alletra.port}`,
    '',
    '# ── HPE iLO / Redfish ────────────────────────────────────',
    `ILO_HOSTS=${cfg.ilo?.hosts ?? ''}`,
    `ILO_USER=${cfg.ilo?.user ?? ''}`,
    `ILO_PASSWORD=${cfg.ilo?.password ?? ''}`,
    `ILO_PORT=${cfg.ilo?.port ?? 443}`,
    `ILO_SSL_VERIFY=${cfg.ilo?.sslVerify ?? false}`,
    `ILO_HOST_MAP=${cfg.ilo?.hostMap ?? ''}`,
    '',
    '# ── Veeam Backup & Replication ────────────────────────────',
    `VEEAM_HOST=${cfg.veeam.host}`,
    `VEEAM_USER=${cfg.veeam.user}`,
    `VEEAM_PASSWORD=${cfg.veeam.password ?? ''}`,
    `VEEAM_PORT=${cfg.veeam.port}`,
    '',
    '# ── App ───────────────────────────────────────────────────',
    `CACHE_TTL_SECONDS=${cfg.cacheTtl ?? 60}`,
    `LOG_LEVEL=${cfg.logLevel ?? 'INFO'}`,
    '',
    '# ── Auth ──────────────────────────────────────────────────',
    `API_KEY=${cfg.apiKey ?? ''}`,
    `ALLOWED_ORIGINS=${cfg.allowedOrigins ?? 'null,http://localhost:5173,http://localhost:8000'}`,
    `FRONTEND_DIST=${cfg.frontendDist ?? ''}`,
    '',
    '# ── Alerting ─────────────────────────────────────────────',
    `WEBHOOK_URL=${cfg.alerts?.webhookUrl ?? ''}`,
    `WEBHOOK_FORMAT=${cfg.alerts?.webhookFormat ?? 'teams'}`,
    `ALERT_INTERVAL_SECONDS=${(cfg.alerts?.alertIntervalMinutes ?? 5) * 60}`,
    '',
    `ALERT_VCENTER_IDLE_VMS=${cfg.alerts?.vcenterIdleVms ?? 1}`,
    `ALERT_VCENTER_OVERSIZED_VMS=${cfg.alerts?.vcenterOversizedVms ?? 5}`,
    `ALERT_VCENTER_CLUSTER_CPU_LOW_PCT=${cfg.alerts?.vcenterClusterCpuLowPct ?? 30}`,
    '',
    `ALERT_ARUBA_UNUSED_PORT_PCT=${cfg.alerts?.arubaUnusedPortPct ?? 30}`,
    '',
    `ALERT_ALLETRA_UTIL_HIGH_PCT=${cfg.alerts?.alletraUtilHighPct ?? 80}`,
    `ALERT_ALLETRA_UTIL_LOW_PCT=${cfg.alerts?.alletraUtilLowPct ?? 20}`,
    `ALERT_ALLETRA_EFFICIENCY_MIN=${cfg.alerts?.alletraEfficiencyMin ?? 2.0}`,
    '',
    `ALERT_VEEAM_FAILED_JOBS=${cfg.alerts?.veeamFailedJobs ?? 1}`,
    `ALERT_VEEAM_UNPROTECTED_VMS=${cfg.alerts?.veeamUnprotectedVms ?? 1}`,
    `ALERT_VEEAM_REPO_UTIL_PCT=${cfg.alerts?.veeamRepoUtilPct ?? 80}`,
    '',
    `ALERT_ILO_POWER_CAP_PCT=${cfg.alerts?.iloPowerCapPct ?? 90.0}`,
    `ALERT_ILO_ERROR_COUNT=${cfg.alerts?.iloErrorCount ?? 1}`,
    '',
    '# ── DNS monitoring ───────────────────────────────────────',
    `DNS_SERVERS=${cfg.dns?.servers ?? ''}`,
    `DNS_CHECK_HOSTS=${cfg.dns?.checkHosts ?? ''}`,
    `DNS_TIMEOUT=${cfg.dns?.timeout ?? 5.0}`,
    '',
    '# ── KACE SMA service desk ────────────────────────────────',
    `KACE_HOST=${cfg.kace?.host ?? ''}`,
    `KACE_USER=${cfg.kace?.user ?? ''}`,
    `KACE_PASSWORD=${cfg.kace?.password ?? ''}`,
    `KACE_ORG=${cfg.kace?.org ?? 'Default'}`,
    `KACE_PORT=${cfg.kace?.port ?? 443}`,
    `KACE_SSL_VERIFY=${cfg.kace?.sslVerify ?? false}`,
    `KACE_HELPDESK_QUEUE=${cfg.kace?.helpdeskQueue ?? 'Helpdesk'}`,
    `KACE_ENGINEERING_QUEUE=${cfg.kace?.engineeringQueue ?? 'Engineering'}`,
    `KACE_TICKET_LIMIT=${cfg.kace?.ticketLimit ?? 500}`,
    '',
    '# ── TLS certificate monitoring ───────────────────────────',
    `CERT_HOSTS=${cfg.certs?.hosts ?? ''}`,
    `CERT_WARN_DAYS=${cfg.certs?.warnDays ?? 30}`,
    `CERT_CRIT_DAYS=${cfg.certs?.critDays ?? 14}`,
    `CERT_TIMEOUT=${cfg.certs?.timeout ?? 10.0}`,
    '',
    '# ── Claude AI (Insights) ─────────────────────────────────',
    `ANTHROPIC_API_KEY=${cfg.claude?.apiKey ?? ''}`,
    `CLAUDE_MODEL=${cfg.claude?.model ?? 'claude-sonnet-4-6'}`,
    '',
    '# ── Terminal Server / RDS ───────────────────────────────',
    `RDS_BROKER=${cfg.rds?.broker ?? ''}`,
    `RDS_HOSTS=${cfg.rds?.hosts ?? ''}`,
    `RDS_WARN_LOAD_PCT=${cfg.rds?.warnLoadPct ?? 75.0}`,
    `RDS_CRIT_LOAD_PCT=${cfg.rds?.critLoadPct ?? 90.0}`,
    '',
    '# ── FortiAnalyzer ───────────────────────────────────────',
    `FORTIANALYZER_HOST=${cfg.fortianalyzer?.host ?? ''}`,
    `FORTIANALYZER_USER=${cfg.fortianalyzer?.user ?? ''}`,
    `FORTIANALYZER_PASSWORD=${cfg.fortianalyzer?.password ?? ''}`,
    `FORTIANALYZER_PORT=${cfg.fortianalyzer?.port ?? 443}`,
    `FORTIANALYZER_SSL_VERIFY=${cfg.fortianalyzer?.sslVerify ?? false}`,
    `FORTIANALYZER_ADOM=${cfg.fortianalyzer?.adom ?? 'root'}`,
    `FORTIANALYZER_DISK_WARN_PCT=${cfg.fortianalyzer?.diskWarnPct ?? 80.0}`,
    `FORTIANALYZER_DISK_CRIT_PCT=${cfg.fortianalyzer?.diskCritPct ?? 90.0}`,
    '',
    '# ── MS Exchange ─────────────────────────────────────────',
    `EXCHANGE_SERVER=${cfg.exchange?.server ?? ''}`,
    `EXCHANGE_USER=${cfg.exchange?.user ?? ''}`,
    `EXCHANGE_PASSWORD=${cfg.exchange?.password ?? ''}`,
    `EXCHANGE_DOMAIN=${cfg.exchange?.domain ?? ''}`,
    `EXCHANGE_TRANSPORT_WARN_QUEUE=${cfg.exchange?.transportWarnQueue ?? 50}`,
    `EXCHANGE_TRANSPORT_CRIT_QUEUE=${cfg.exchange?.transportCritQueue ?? 200}`,
    '',
    '# ── FortiGate firewall ───────────────────────────────────',
    `FORTIGATE_HOST=${cfg.fortigate?.host ?? ''}`,
    `FORTIGATE_TOKEN=${cfg.fortigate?.token ?? ''}`,
    `FORTIGATE_PORT=${cfg.fortigate?.port ?? 443}`,
    `FORTIGATE_SSL_VERIFY=${cfg.fortigate?.sslVerify ?? false}`,
    `FORTIGATE_VDOM=${cfg.fortigate?.vdom ?? 'root'}`,
    `FORTIGATE_WARN_CPU_PCT=${cfg.fortigate?.warnCpuPct ?? 70.0}`,
    `FORTIGATE_CRIT_CPU_PCT=${cfg.fortigate?.critCpuPct ?? 90.0}`,
    '',
    '# ── Wall TV display ─────────────────────────────────────',
    `TV_MODE_ENABLED=${cfg.tv?.enabled ?? false}`,
    `TV_MODE_RESOLUTION=${cfg.tv?.resolution ?? 'hd'}`,
    `TV_MODE_REFRESH_SECONDS=${cfg.tv?.refreshSeconds ?? 30}`,
    '',
    '# ── SIEM integration ─────────────────────────────────────',
    `SIEM_ENABLED=${cfg.siem?.enabled ?? false}`,
    `SIEM_PUSH_URL=${cfg.siem?.pushUrl ?? ''}`,
    `SIEM_PUSH_API_KEY=${cfg.siem?.pushApiKey ?? ''}`,
    `SIEM_RETAIN_DAYS=${cfg.siem?.retainDays ?? 30}`,
  ].join('\n')
}
